### ISSUE TITLE
WindowSize not supported on "linux" (WSL2)

### ISSUE THREAD

**Issue by boekabart** [MichalStrehovsky/SeeSharpSnake#3]
```sh
bart@myLaptopWithWsl2:~/SeeSharpSnake$ dotnet run -r linux-x64
Unhandled exception. System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowSize(Int32 width, Int32 height)
   at System.Console.SetWindowSize(Int32 width, Int32 height)
   at Game.Main() in /home/bart/SeeSharpSnake/Game/Game.cs:line 91
```
I guess the only solution would be getting `#if` fy ?

**Comment by boekabart** [comment]
Of course, I this is only for the non-optimized version... the optimized ones shouldn't even work as you indicate in the medium article.

**Comment by MichalStrehovsky** [comment]
I sketched out the fix for that here: https://medium.com/p/de8a268fe792/responses/show

People clapped for it, but nobody came up with a pull request.

**Comment by boekabart** [comment]
I locally 'commented out' the 4 lines of 'Console init' with an `#if Windows`, that made it work... with some graphical challenges ;)
